import Head from 'next/head'
import { useEffect, useState } from 'react';
import NavBar from '../components/NavBar'
import Slider from '../components/Slider'
export default function Home() {
  const [isSessionActive, setIsSessionActive] = useState(undefined);
  useEffect(() => {
    const session = localStorage.getItem("session");
    if (session) {
      setIsSessionActive(true);
    } else {
      setIsSessionActive(false);
    }
  }, [isSessionActive]);
  return (
    <>
      <Head>
        <title>JSSPORT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar
        session={isSessionActive}
        setSession={setIsSessionActive}
      />
      <Slider />
    </>
  )
}
